Fixing - php error was thrown out because of variable reference
production.ERROR: exception 'ErrorException' with message 'Only variables should be passed by reference' in /var/www/html/sandbox/app/routes.php:79